config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  get 'welcome/index'

  resources :events

  root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def show
    @article = Article.find(params[:id])
  end

  def new
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to @article
  end

  private
  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all.order(:datetime)
    @user = session['session_id']
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @pretty_date = @event[:datetime].strftime("%b %-d")
    @date_ordinal = @event[:datetime].day.ordinal
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.fetch(:event).permit(:year, :month, :day, :hour, :minute, :datetime, :city, :state, :venue, :image, :description)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= form_for :article, url: articles_path do |f| %>

<p>
  <%= f.label :title %>
  <%= f.text_field :title %>
</p>

<p>
  <%= f.label :text %>
  <%= f.text_area :text %>
</p>

<p>
  <%= f.submit class: 'button' %>
</p>

<% end %>

app/views/articles/show.html.erb
<p class="copy-default">
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p class="copy-default">
  <strong>Text:</strong>
  <%= @article.text %>
</p>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation" class="panel danger">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul class="copy-default">
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="actions">

    <fieldset class="full-width">
      <%= f.label :datetime, 'Date / Time' %>
      <%= f.datetime_select :datetime %>
    </fieldset>

    <fieldset>
      <%= f.label :city %>
      <%= f.text_field :city %>
    </fieldset>

    <fieldset>
      <%= f.label :state %>
      <%= f.text_field :state %>
    </fieldset>

    <fieldset class="full-width">
      <%= f.label :venue %>
      <%= f.text_field :venue, class: 'full-width' %>
    </fieldset>

    <fieldset>
      <%= f.label :image %>
      <%= f.file_field :image %>
    </fieldset>

    <fieldset class="full-width">
      <%= f.label :description %>
      <%= f.text_area :description, class: 'full-width' %>
    </fieldset>

    <%= f.submit class: 'button' %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event, class: 'link-default' %> |
<%= link_to 'Back', events_path, class: 'link-default' %>

app/views/events/index.html.erb
<h1>All Events</h1>
<%= link_to 'New Event', new_event_path, class: 'button' %>

<ul>
<% session.instance_variables.each do |attribute| %>
  <li><%= attribute %></li>
<% end %>
</ul>

<% @events.each do |event| %>
<div class="panel admin dark">
  <a href="<%= event_path(event[:id]) %>" class="link-default">
    <h2><%= event.datetime.strftime("%b %-d") %></h2>
    <h3><%= event[:city] %></h3>
  </a>
  <%= link_to 'View', event, class: 'button' %>
  <%= link_to 'Edit', edit_event_path(event), class: 'button' %>
  <%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button' %>
</div>
<% end %>

<%= link_to 'New Event', new_event_path, class: 'button' %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path, class: 'link-default' %>

app/views/events/show.html.erb
<article class="card">
  <header class="card__header">
    <h1 class="card__date">
      <time datetime="<%= @event.datetime %>">
        <%= @pretty_date %><span class="text-super"><%= @date_ordinal %></span>
      </time>
    </h1>
    <h2 class="card__city text-xl"><%= @event.city %>, <%= @event.state %></h2>
    <h3 class="card__venue  text-xl"><%= @event.venue %></h3>
  </header>
  <figure class="badge card__poster">
    <%# TODO: GET image.tall/wide image.src image.alt %>
    <%= image_tag @event.image.url(:medium) %>
    <!-- <img class="" src="<%= @event.image %>" alt=""> -->
  </figure>
  <p class="copy-default card__desc">
    <%= @event.description %>
  </p>
  <footer class="card__footer">
    <ul class="card__footer-links">
      <%# TODO: GET event.links %>
      <li><a class="button card__footer-link" href="#">Tickets</a></li>
      <li><a class="button card__footer-link" href="#">Map</a></li>
      <li><a class="button card__footer-link" href="#">More Info</a></li>
    </ul>
  </footer>
</article>

<%= link_to 'Edit', edit_event_path(@event), class: 'link-default' %> |
<%= link_to 'Back', events_path, class: 'link-default' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
	<meta http-equiv="x-ua-compatible" content="ie=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
  <title>EventCards</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="user-controls">
    <% if user_signed_in? %>
      <%= link_to "Sign out", destroy_user_session_path, :method => :delete, class: 'button user-controls__link' %>
    <% end %>
  </div>

  <main class="main">
    <%= yield %>
  </main>

  <% if notice %>
  <p id="notice" class="panel light">
    <%= notice %>
    <%= link_to 'x', '', class: 'notice__dismiss' %>
  </p>
  <% end %>
  <% if alert %>
  <p id="alert" class="panel light caution"><%= alert %>
    <%= link_to 'x', '', class: 'alert__dismiss' %>
  </p>
  <% end %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Hi :)</h1>
<h1>THIS IS A TEST!</h1>
<%= link_to 'Check out the event listing ➞', '/events', class: 'link-default' %>